server:
  port: 8888

spring:
  application:
    name: springcloud_eureka

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka/
