server:
  port: 50201
spring:
  application:
    name: xc-service-gateway
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: http://127.0.0.1:8848
    gateway:
      routes:
        - id: ucenter_auth
          uri: lb://xc-service-ucenter-auth
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
            - Log=file
