server:
  port: 50201
spring:
  application:
    name: xc-service-gateway
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: http://127.0.0.1:8848
    gateway:
<<<<<<< HEAD
      discovery:
        locator:
          enabled: true
=======
>>>>>>> origin/master
      routes:
        - id: ucenter_auth
          uri: lb://xc-service-ucenter-auth
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
<<<<<<< HEAD
        - id: ucenter
          uri: lb://xc-service-ucenter
          predicates:
            - Path=/api/ucenter/**
          filters:
            - StripPrefix=1
        - id: framework-course
          uri: lb://xc-framework-course
          predicates:
            - Path=/api/course/**
          filters:
            - StripPrefix=1
=======
            - Log=file
>>>>>>> origin/master
